name: release skglm

on:
  pull_request:
    branches:
      - 'main'

jobs:
  release_skglm:
    name: Release skglm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install skglm
        run: pip install .

      - name: Build source dist
        run: |
          python3 -m pip install --upgrade build
          python3 -m build --sdist

      # - name: publish to Test PyPI
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #   run: |
      #     pip install twine
      #     twine upload --skip-existing --repository testpypi dist/*.tar.gz

      - name: publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --skip-existing dist/*.tar.gz
